/*тергера*/
tee trg.log

use test2; 

DROP TRIGGER IF EXISTS APP1$OWNERS_BU_TRG;

delimiter |

CREATE TRIGGER APP1$OWNERS_BU_TRG BEFORE UPDATE ON APP1$OWNERS
  FOR EACH ROW
  BEGIN
    SET NEW.MDT = CURRENT_TIMESTAMP();
    SET NEW.MUSRNM = USER();
    SET NEW.FIRSTNAME = TRIM(NEW.FIRSTNAME) ;   
    SET NEW.LASTNAME = TRIM(NEW.LASTNAME) ;   
  END;
|

delimiter ;