/*тергера*/
tee trg.log

use test2; 

DROP TRIGGER IF EXISTS APP1$OWNERS_BI_TRG;

delimiter |

CREATE TRIGGER APP1$OWNERS_BI_TRG BEFORE INSERT ON APP1$OWNERS
  FOR EACH ROW
  BEGIN
    SET NEW.IDT = CURRENT_TIMESTAMP();
    SET NEW.IUSRNM = USER();
    SET NEW.FIRSTNAME = TRIM(NEW.FIRSTNAME) ;   
  END;
|

delimiter ;