SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;



select T.TRNID, T.DTTRN, T.SUM, T.PROC_STATUS, D.CUSTID as DBT_CUSTID, D.SUM AS DBTRST, K.CUSTID as KRD_CUSTID, K.SUM AS KRDRST
from app2$trn T
INNER join app2$cust d on d.CUSTID = T.DBT_CUSTID
INNER join app2$cust k on k.CUSTID = T.KRD_CUSTID;


call APP2_TRNPROC(NULL);


call APP2_TRNPROC(333);



call APP2_TRNPROC(1);


call APP2_TRNPROC(2);

select T.TRNID, T.DTTRN, T.SUM, T.PROC_STATUS, D.CUSTID as DBT_CUSTID, D.SUM AS DBTRST, K.CUSTID as KRD_CUSTID, K.SUM AS KRDRST
from app2$trn T
INNER join app2$cust d on d.CUSTID = T.DBT_CUSTID
INNER join app2$cust k on k.CUSTID = T.KRD_CUSTID;




